apiVersion: v1
kind: Service
metadata:
  name: nodejs-demo-app-service
  namespace: nodejs-demo-app
spec:
  selector:
    app: nodejs-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP